AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  LumiLore Backend API

Globals:
  Function:
    Timeout: 10
    MemorySize: 128

Resources:
  # The Serverless API Lambda Function
  LumiLoreApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: backend/src/
      Handler: app.lambdaHandler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /api/status
            Method: get

Outputs:
  LumiLoreApiUrl:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/api/status"
